### ISSUE TITLE
LinearLocationReference.decode_relative ignores the negative bit

### ISSUE THREAD

**Issue by JPA2015** [FraunhoferIVI/openlr#17]
The endpoint in an openlr string like CCkBEAAlJAi8NSSC8wAJBQQDAwEACgUEA45fAP9NBmwACQUEAwOAADAAAA== has negative relative coordinates. The expected coordinates for this endpoint would be latitude=51.3607548 and longitude=12.2820514.

The function LinearLocationReference.decode_relative doesn't seem to decode negative values correctly. Code similar to the "if negative bit set" in GeoCoordinateLocationReference.decode_absolute would probably correct the problem.

**Comment by stefanhahmann** [comment]
Thanks for pointing this out. Can you provide a Unit-Test proving this?
Then we could start thinking about a potential fix.

The method `decode_relative` had been translated from C#-Code.

The original C#-Code is here:

`public static int decode_relative(byte[] buf)
 {
// Read first 2 bytes for Longitude
short upperVal = (short) (buf[0] << 8);
short lowerVal = buf[1];
int relativeVal =  upperVal | lowerVal;
return relativeVal;
}`

I can see some differences in the current Java translation in this repo that may cause this. Perhaps you could try to improve the translated code and test again?

**Comment by JPA2015** [comment]
Thanks for your answer.
Actually I translated the code to yet another language and now that you point it, the problem might come from my translation. I will test with the Java code again and inform you later.

**Comment by JPA2015** [comment]
I wasn't able to reproduce it with Java code. The problem was then with my translation of the code. Sorry for that.
